---
- src: https://github.com/bsalisbury-emergent360/launch_rhel_cluster.git
- src: https://github.com/bsalisbury-emergent360/teardown_rhel_cluster.git
- src: https://github.com/bsalisbury-emergent360/register_rhel_subscription.git
- src: https://github.com/bsalisbury-emergent360/deregister_rhel_subscription.git
- name: RedHatOfficial.rhel8_ospp